[package]
name = "connect-four-ai"
version = "0.1.0"
authors = ["Monlih <MonliH@users.noreply.github.com>"]
edition = "2018"


[dependencies]
rand = "0.7"
rayon = "1.3.0"

serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.1"

